### ISSUE TITLE
Provide ReasonerStd query API

### ISSUE THREAD

**Issue by cbizon** [NCATS-Tangerine/icees-api#20]
There is an API that implements the reasoner API, but it is not a generic query api.  The current API (as I understand it) takes a cohort as an option, then performs some kind of disproportionality analysis between that cohort and the set difference of the universal cohort and the input cohort, and returns edges from the cohort to the entity that is disproportionately represented.

I suggest 2 changes:

1. The above workflow/query is quite different from the rest of the ICEES approach.  In the rest of icees, you define a cohort, and then look for associations between entities within that defined cohort.   I think that the query API should do the same.  

2. The machine question should be fully generalized to allow for any query, not just population to feature. 

That may be a lot of work, but here are a series of iterations that would each be useful, in my opinion.

First, a query that can answer any one hop within the universal cohort
Second, extend that to taking the cohort as an option in the query
Third, extend to answering arbitrary-shaped queries
Fourth, providing partial matches to arbitrary shaped queries.

**Comment by karafecho** [comment]
I think I understand Chris' point, but I also think that the concept of a 'universal cohort' is creating some confusion, at least for me. Another source of confusion may be the forced fit to Biolink, with a reliance on semantic types such as 'population_of_living_organisms'. Just my two cents...

**Comment by karafecho** [comment]
@xu-hao will address this issue on or before June 12.

**Comment by cbizon** [comment]
All I meant for universal cohort is the cohort that includes everybody in icees.  Does that make sense?

I don't think population_of_living_organisms is relevant to step 1, though I suspect that there will be other mapping difficulties.

**Comment by karafecho** [comment]
Yes, I understood your intent, but I think it makes more sense to think in terms of 'features'. For instance, 'universal cohort' might mean 'all patients in year 2010', all 'UNC Health patients in 2010', all 'EPR participants in 2010', 'all UNC Health and EPR participants in 2010', etc. As we develop new use cases, we'll need to refine this even further, e.g., 'all UNC Health patients within asthma-like cohort in 2010', 'all UNC Health patients within PCD cohort in 2010', etc. I guess what I'm trying to emphasize is that there's always going to be some set of features to define what population you are interested in. So, my suggestion would be to point to features of interest, rather than cohorts.

**Comment by cbizon** [comment]
> I guess what I'm trying to emphasize is that there's always going to be some set of features to define what population you are interested in. 

This is a really important statement, and I think the nub of the issue.  I would argue that there is sometimes such a set of features, and sometimes there isn't.   A lot of times I want 'general' knowledge.  I'm willing to take contextual information and pretend that it's general, or use it as if it was general, but I don't have any way to decide a priori what context to ask for.

**Comment by karafecho** [comment]
I guess I would argue that *all knowledge* is contextual, and I think you sort of agree with that, but I'm not sure I fully understand your concern. 

If the data offered by the ICEES+ KP is registered somewhere, then wouldn't you at least be able to specify the general 'cohort' or set of features of interest? Instead of 'universal cohort'?

Let's find a time to discuss. See my comment under #21.
